### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by svx** [plone/simple-plone-buildout#1]
A reminder for: https://github.com/plone/documentation/issues/758

- [x] Update README
- [x] have docs about requirements
- [x] compare to unified installer
- [x] add license
- [x] split up huge *** README
- [ ] ...

WIP in its own branch: https://github.com/plone/simple-plone-buildout/tree/pimp_da_docs

**Comment by tkimnguyen** [comment]
I made many changes to README.rst in https://github.com/plone/simple-plone-buildout/tree/5.0.7-with-docs

**Comment by tkimnguyen** [comment]
@svx since I don't actually see a tag "pimp_da_docs" I'll assume that was just a placeholder. I'm going to move some things around the README to make it clearer.

**Comment by svx** [comment]
@tkimnguyen I just opened a PR ! :)

I moved,changed, improved a lot, only what is IMHO missing are:

- explanation between differences to UI 
- link to dependencies for UNIX

**Comment by svx** [comment]
@tkimnguyen there wea old branch 'pimp da docs' which I deleted in favor of the new branch and the resulting PR :)

**Comment by tkimnguyen** [comment]
See https://github.com/plone/simple-plone-buildout/commit/4d55a97425cf4c29dd15050572171e23a9f6dcd1

**Comment by tkimnguyen** [comment]
Oops, clash! I'll look at your PR :)

**Comment by tkimnguyen** [comment]
@svx I'll let you figure it out :) but I put a bunch of work in it so don't just throw it away please!

**Comment by svx** [comment]
@tkimnguyen My branch is  based on your changes from 10 hrs ago, so I have the pictures and so on

**Comment by svx** [comment]
@tkimnguyen Ok please do not add more stuff, I will include your latest changes I am missing and ill create a new PR.
Hold your horses for a couple of minutes !

**Comment by tkimnguyen** [comment]
I'm done! Thx @svx !!! CLEAR!

**Comment by svx** [comment]
OK, done so far, what we are still missing:
- explanation of differences between this repo here and the UI [Unified Installer]

**Comment by cadhage** [comment]
Hi Sir,

 From 2 days, I am facing one issue regarding  "using the simple plone built-out".
Actually, from few days I have been working on my GSoC proposal and thus I want develop the quick
 project using plone, so that my mentor can understand how I am going to built my project and 
what will be my approach. For that purpose proper installation is needed . So please help me . 
I am sending screen shot as attachment so that you can understand my problem.

Thanks in advance,
Regard,
C T. Adhage

Attachment:-
![capture9](https://cloud.githubusercontent.com/assets/25525036/24273164/efc52b12-1046-11e7-9a20-de553cd98f07.JPG)

**Comment by tkimnguyen** [comment]
@cadhage this is not the place to ask for support; please use the forum https://community.plone.org instead

**Comment by tkimnguyen** [comment]
@svx are we done with this issue?

**Comment by lidymonteirowm** [comment]
@cadhage I have the same problem. How did you solve it?

**Comment by tkimnguyen** [comment]
@lidymonteirowm please ask for help in the Plone forum at https://community.plone.org
